name: Deploy Sales Notebook to Databricks

on:
  push:
    branches:
      - main

jobs:

  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks DEV
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DEV_HOST }}
          ${{ secrets.DEV_TOKEN }}
          EOF

      - name: Deploy Notebook to DEV
        run: |
          databricks workspace import_dir ${{vars.NOTEBOOK_FOLDER}} ${{vars.DEV_WORKSPACE_PATH}} --overwrite


  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks PROD
        run: |
          databricks configure --token <<EOF
          ${{ secrets.PROD_HOST }}
          ${{ secrets.PROD_TOKEN }}
          EOF

      - name: Deploy Notebook to PROD
        run: |
          databricks workspace import_dir ${{vars.NOTEBOOK_FOLDER}} ${{vars.PROD_WORKSPACE_PATH}} --overwrite
